//! This module compiles temporary Typst files and manages output files.
//!
//! The compile module has two primary functions:
//!
//! 1. Compile the temporary Typst file generated by the `generate` module using
//!    the appropriate Typst commands (PNG, SVG, or both based on note formats).
//!
//! 2. Associate output files with corresponding notes and fields. It queries the
//!    Typst file for metadata using the `query` module and builds a vector of
//!    `Note` structs. Output files are systematically renamed using the format:
//!    `<label>@@<field>@@<timestamp>.<format>` and added to the `picture` field
//!    of the `Note` struct. For Plain format, no output file is generated and
//!    the string value is passed directly to the note's fields.

use crate::ankiconnect::{Deck, Field, FieldValue, MediaFile, Model, Note as AnkiNote, Tag};
use crate::error::{Error, Result};
use crate::metadata::CompletedNote;
use crate::query;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use tokio::process::Command as AsyncCommand;

/// Get the root path for the monorepo (for --root flag).
fn get_root_path() -> Result<PathBuf> {
    // Try to get CARGO_MANIFEST_DIR first (for development)
    if let Ok(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR") {
        return std::path::PathBuf::from(manifest_dir)
            .parent() // packages
            .ok_or_else(|| Error::custom("Cannot find packages directory"))?
            .parent() // ankify root
            .ok_or_else(|| Error::custom("Cannot find monorepo root"))
            .map(|p| p.to_path_buf());
    }

    // Fallback: use current directory for release builds
    std::env::current_dir()
        .map_err(|e| Error::custom(format!("Cannot get current directory: {}", e)))
}

/// Format types for rendering note fields.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Format {
    /// Plain text format - no compilation needed.
    Plain,
    /// SVG vector format.
    Svg,
    /// PNG raster format.
    Png,
}

impl Format {
    /// Get the file extension for this format.
    pub fn extension(&self) -> &'static str {
        match self {
            Format::Plain => "txt",
            Format::Svg => "svg",
            Format::Png => "png",
        }
    }

    /// Get the typst format argument for this format.
    pub fn typst_arg(&self) -> &'static str {
        match self {
            Format::Plain => panic!("Plain format should not be compiled"),
            Format::Svg => "svg",
            Format::Png => "png",
        }
    }
}

impl From<&str> for Format {
    fn from(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "plain" => Format::Plain,
            "svg" => Format::Svg,
            "png" => Format::Png,
            _ => Format::Png, // Default to PNG for unknown formats
        }
    }
}

/// Configuration for compiling Typst files.
#[derive(Debug, Clone)]
pub struct CompileConfig {
    /// The temporary Typst file to compile.
    pub temp_file: PathBuf,
    /// The source Typst file (for root directory calculation).
    pub source_file: PathBuf,
    /// Output directory for compiled files.
    pub output_dir: PathBuf,
    /// Additional arguments to pass to typst compile.
    pub extra_args: Vec<String>,
    ///
    pub completed_notes_metadata: Vec<CompletedNote>,
    ///
    pub required_formats: Vec<Format>,
}

impl CompileConfig {
    /// Create a new compile configuration.
    pub fn new(
        temp_file: PathBuf,
        source_file: PathBuf,
        output_dir: PathBuf,
        completed_notes_metadata: Vec<CompletedNote>,
    ) -> Self {
        Self {
            temp_file,
            source_file,
            output_dir,
            extra_args: Vec::new(),
            required_formats: query::determine_required_formats(&completed_notes_metadata),
            completed_notes_metadata,
        }
    }

    /// Add extra arguments to the typst compile command.
    pub fn with_extra_args(mut self, args: Vec<String>) -> Self {
        self.extra_args = args;
        self
    }
}

/// Result of a compilation operation.
#[derive(Debug)]
pub struct CompileResult {
    /// The notes with associated media files.
    pub notes: Vec<AnkiNote>,
    /// Paths to generated output files.
    pub output_files: HashMap<Format, Vec<PathBuf>>,
}

#[derive(Debug)]
pub struct FilesWithFormat {
    /// The format of the files.
    pub format: Format,
    /// The list of output files generated for this format.
    pub files: Vec<PathBuf>,
}

/// Compile a temporary Typst file and generate Anki notes.
///
/// This function:
/// 1. Queries the temporary file for note metadata
/// 2. Determines which formats need to be compiled
/// 3. Runs the appropriate typst compile commands
/// 4. Associates output files with notes and fields
/// 5. Returns structured note data for AnkiConnect
///
/// # Arguments
///
/// * `config` - Compilation configuration
///
/// # Returns
///
/// Returns a `CompileResult` containing the generated notes and output file paths.
///
/// # Errors
///
/// Returns an error if:
/// - The temporary file cannot be queried for metadata
/// - Typst compilation fails
/// - Output files cannot be read or renamed
pub async fn compile_temp_file(config: &CompileConfig) -> Result<CompileResult> {
    if config.completed_notes_metadata.is_empty() {
        return Ok(CompileResult {
            notes: Vec::new(),
            output_files: HashMap::new(),
        });
    }

    // Compile the files for each required format, in parallel
    let futures: Vec<_> = config
        .required_formats
        .iter()
        .map(|format| {
            let format_clone = format.clone();
            async move {
                let files = compile_format(config, &format_clone).await;
                (format_clone, files)
            }
        })
        .collect();
    let results = futures::future::join_all(futures).await;
    let mut output_files = HashMap::new();
    for (format, files_result) in results {
        let files = files_result?;
        output_files.insert(format, files);
    }

    // Associate output files with notes and fields
    let notes =
        associate_files_with_notes(config, &config.completed_notes_metadata, &output_files).await?;

    Ok(CompileResult {
        notes,
        output_files,
    })
}

/// Compile the temporary file for a specific format.
async fn compile_format(config: &CompileConfig, format: &Format) -> Result<Vec<PathBuf>> {
    // Use {p} pattern to generate one file per page
    let output_pattern = config
        .output_dir
        .join(format!("output-{{p}}.{}", format.extension()));

    // Check if extra_args contains a custom --root, otherwise use default
    let mut custom_root = None;
    let mut i = 0;
    while i < config.extra_args.len() {
        if config.extra_args[i] == "--root" && i + 1 < config.extra_args.len() {
            custom_root = Some(&config.extra_args[i + 1]);
            break;
        }
        i += 1;
    }

    let root_dir = match custom_root {
        Some(root) => std::path::PathBuf::from(root),
        None => get_root_path()?,
    };

    // Build the typst compile command
    let mut cmd = AsyncCommand::new("typst");
    cmd.arg("compile")
        .arg("--format")
        .arg(format.typst_arg())
        .arg("--root")
        .arg(root_dir)
        .arg(&config.temp_file)
        .arg(&output_pattern);

    // Add any extra arguments (but skip --root args since we handled them)
    let mut skip_next = false;
    for arg in &config.extra_args {
        if skip_next {
            skip_next = false;
            continue;
        }
        if arg == "--root" {
            skip_next = true;
            continue;
        }
        cmd.arg(arg);
    }

    // Execute the command
    let output = cmd
        .output()
        .await
        .map_err(|e| Error::custom(format!("Failed to execute typst compile: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::custom(format!(
            "Typst compilation failed: {}",
            stderr
        )));
    }

    // Find all generated output files (output-1.ext, output-2.ext, etc.)
    let mut output_files = Vec::new();
    let output_dir = config.output_dir.as_path();

    if output_dir.exists() {
        let entries = fs::read_dir(output_dir).map_err(|e| {
            Error::custom(format!(
                "Failed to read output directory {}: {}",
                output_dir.display(),
                e
            ))
        })?;

        for entry in entries {
            let entry = entry
                .map_err(|e| Error::custom(format!("Failed to read directory entry: {}", e)))?;

            let path = entry.path();
            if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                // Check for pattern: output-<number>.extension
                if filename.starts_with("output-")
                    && path
                        .extension()
                        .map_or(false, |ext| ext == format.extension())
                {
                    output_files.push(path);
                }
            }
        }
    }

    // Sort output files by page number to ensure consistent ordering
    output_files.sort_by(|a, b| {
        let extract_page_num = |path: &PathBuf| -> u32 {
            path.file_stem()
                .and_then(|stem| stem.to_str())
                .and_then(|s| s.strip_prefix("output-"))
                .and_then(|s| s.parse().ok())
                .unwrap_or(0)
        };
        extract_page_num(a).cmp(&extract_page_num(b))
    });

    Ok(output_files)
}

/// Associate output files with notes and fields.
async fn associate_files_with_notes(
    _config: &CompileConfig,
    metadata_notes: &[CompletedNote],
    output_files: &HashMap<Format, Vec<PathBuf>>,
) -> Result<Vec<AnkiNote>> {
    let mut anki_notes = Vec::new();
    let timestamp = chrono::Utc::now().timestamp();

    // Create a mapping of (note_index, field_name) to output file
    let file_associations = create_file_associations(metadata_notes, output_files)?;

    for (note_index, metadata_note) in metadata_notes.iter().enumerate() {
        let mut fields = HashMap::new();
        let mut picture_files = Vec::new();

        // Sort field names to ensure consistent ordering (as per documentation)
        let mut sorted_fields: Vec<_> = metadata_note.data.keys().collect();
        sorted_fields.sort();

        for field_name in sorted_fields {
            let field_value = &metadata_note.data[field_name];
            let field_format = Format::from(field_value.format.as_str());
            let output_file = file_associations.get(&(note_index, field_name.as_str()));
            match field_format {
                Format::Plain => {
                    // Plain text goes straight into the field.
                    fields.insert(
                        Field::new(field_name.clone()),
                        FieldValue::new(field_value.value.clone()),
                    );
                }
                Format::Svg => {
                    // SVG is inlined directly into the field, recoloured so it
                    // follows the Anki card's (themed) text colour. Being part
                    // of the card's DOM, an inline SVG can use `currentColor`;
                    // an `<img>`-embedded SVG could not. No media file needed.
                    match output_file.and_then(|files| files.get(&Format::Svg)) {
                        Some(svg_path) => {
                            let svg = fs::read_to_string(svg_path).map_err(|e| {
                                Error::custom(format!(
                                    "Failed to read SVG '{}': {}",
                                    svg_path.display(),
                                    e
                                ))
                            })?;
                            fields.insert(
                                Field::new(field_name.clone()),
                                FieldValue::new(Some(theme_svg(&svg))),
                            );
                        }
                        None => {
                            fields.insert(
                                Field::new(field_name.clone()),
                                FieldValue::new(field_value.value.clone()),
                            );
                        }
                    }
                }
                Format::Png => {
                    // PNG is stored as an Anki media file, referenced via the
                    // note's `picture` array.
                    if let Some(output_file) = output_file {
                        let media_file = create_media_file(
                            output_file,
                            &metadata_note.label,
                            field_name,
                            timestamp,
                            &field_format,
                        )?;
                        fields.insert(
                            Field::new(field_name.clone()),
                            FieldValue::new(Some(String::new())),
                        );
                        picture_files.push(media_file);
                    } else {
                        fields.insert(
                            Field::new(field_name.clone()),
                            FieldValue::new(field_value.value.clone()),
                        );
                    }
                }
            }
        }

        // Create the Anki note
        let anki_note = AnkiNote {
            deck_name: Deck::new(metadata_note.deck.clone()),
            model_name: Model::new(metadata_note.model.clone()),
            fields,
            tags: Some(
                metadata_note
                    .tags
                    .iter()
                    .map(|tag| Tag::new(tag.clone()))
                    .collect(),
            ),
            options: None,
            audio: None,
            video: None,
            picture: if picture_files.is_empty() {
                None
            } else {
                Some(picture_files)
            },
        };

        anki_notes.push(anki_note);
    }

    Ok(anki_notes)
}

/// Create a mapping of (note_index, field_name) to record { [format]: output_file }.
fn create_file_associations<'a>(
    metadata_notes: &'a [CompletedNote],
    output_files: &'a HashMap<Format, Vec<PathBuf>>,
) -> Result<HashMap<(usize, &'a str), HashMap<Format, PathBuf>>> {
    let mut associations = HashMap::new();

    // For each format, get a reference to the Vec<PathBuf>
    let mut format_to_files: HashMap<Format, &Vec<PathBuf>> = HashMap::new();
    for (format, files) in output_files.iter() {
        format_to_files.insert(format.clone(), files);
    }

    // For each field, we need to know which index it is in the global field order
    // The order is: for all notes, for all fields (sorted), in order
    let mut global_field_index = 0;
    for (note_index, metadata_note) in metadata_notes.iter().enumerate() {
        let mut sorted_fields: Vec<_> = metadata_note.data.keys().collect();
        sorted_fields.sort();

        for field_name in sorted_fields {
            // For this (note_index, field_name), build a HashMap<Format, PathBuf>
            let mut field_files = HashMap::new();
            for (format, files) in &format_to_files {
                if global_field_index < files.len() {
                    field_files.insert(format.clone(), files[global_field_index].clone());
                }
            }
            associations.insert((note_index, field_name.as_str()), field_files);
            global_field_index += 1;
        }
    }

    Ok(associations)
}

/// Recolour a Typst-rendered SVG so it adapts to the Anki card's theme.
///
/// The card pages are rendered with no page fill, so the SVG is already
/// transparent and the card's own (light/dark) background shows through. The
/// foreground is rendered black by Typst; rewriting it to `currentColor` makes
/// it follow the card's CSS `color`, which Anki themes for light/dark mode.
/// Non-black colours (e.g. a coloured diagram) are deliberately left untouched.
fn theme_svg(svg: &str) -> String {
    svg.replace("fill=\"#000000\"", "fill=\"currentColor\"")
        .replace("stroke=\"#000000\"", "stroke=\"currentColor\"")
}

/// Create a media file from an output file.
pub fn create_media_file(
    output_file: &HashMap<Format, PathBuf>,
    note_label: &str,
    field_name: &str,
    timestamp: i64,
    format: &Format,
) -> Result<MediaFile> {
    // AnkiConnect resolves a media file's `path` relative to Anki's own working
    // directory, not ours — so it must be sent as an absolute path.
    let path = &output_file[format];
    let absolute_path = std::fs::canonicalize(path).map_err(|e| {
        Error::custom(format!(
            "Failed to resolve output file path '{}': {}",
            path.display(),
            e
        ))
    })?;

    Ok(MediaFile {
        filename: format!(
            "{}@@{}@@{}.{}",
            note_label,
            field_name,
            timestamp,
            format.extension()
        ),
        data: None,
        path: Some(absolute_path.to_string_lossy().to_string()),
        url: None,
        skip_hash: None,
        fields: Some(vec![Field::new(field_name.to_string())]),
    })
}

/// Clean up output files in the given directory.
///
/// This function removes all files matching the pattern `output-*` in the
/// specified directory.
///
/// # Arguments
///
/// * `dir` - The directory to clean up
///
/// # Errors
///
/// Returns an error if the directory cannot be read or files cannot be removed.
pub fn cleanup_output_files(dir: &Path) -> Result<()> {
    if !dir.exists() {
        return Ok(()); // Nothing to clean up
    }

    let entries = fs::read_dir(dir)
        .map_err(|e| Error::custom(format!("Failed to read directory {}: {}", dir.display(), e)))?;

    for entry in entries {
        let entry = entry.map_err(|e| {
            Error::custom(format!(
                "Failed to read directory entry in {}: {}",
                dir.display(),
                e
            ))
        })?;

        let path = entry.path();
        if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
            // Clean up both pattern: output-<number>.ext and temp render files
            if filename.starts_with("output-") || filename.ends_with("_render.typ") {
                fs::remove_file(&path).map_err(|e| {
                    Error::custom(format!(
                        "Failed to remove output file {}: {}",
                        path.display(),
                        e
                    ))
                })?;
            }
        }
    }

    Ok(())
}
