//! This module compiles temporary Typst files and manages output files.
//!
//! The compile module has two primary functions:
//!
//! 1. Compile the temporary Typst file generated by the `generate` module using
//!    the appropriate Typst commands (PNG, SVG, or both based on note formats).
//!
//! 2. Associate output files with corresponding notes and fields. It queries the
//!    Typst file for metadata using the `query` module and builds a vector of
//!    `Note` structs. Output files are systematically renamed using the format:
//!    `<label>@@<field>@@<timestamp>.<format>` and added to the `picture` field
//!    of the `Note` struct. For Plain format, no output file is generated and
//!    the string value is passed directly to the note's fields.

use crate::ankiconnect::{Deck, Field, FieldValue, MediaFile, Model, Note, Tag};
use crate::error::{Error, Result};
use crate::metadata::Note as MetadataNote;
use crate::query::query_ankify_notes;
use base64::Engine;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use tokio::process::Command as AsyncCommand;

/// Get the root path for the monorepo (for --root flag).
fn get_root_path() -> Result<PathBuf> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .map_err(|_| Error::custom("CARGO_MANIFEST_DIR not set"))?;

    std::path::PathBuf::from(manifest_dir)
        .parent() // packages
        .ok_or_else(|| Error::custom("Cannot find packages directory"))?
        .parent() // ankify root
        .ok_or_else(|| Error::custom("Cannot find monorepo root"))
        .map(|p| p.to_path_buf())
}

/// Format types for rendering note fields.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Format {
    /// Plain text format - no compilation needed.
    Plain,
    /// SVG vector format.
    Svg,
    /// PNG raster format.
    Png,
}

impl Format {
    /// Get the file extension for this format.
    pub fn extension(&self) -> &'static str {
        match self {
            Format::Plain => "txt",
            Format::Svg => "svg",
            Format::Png => "png",
        }
    }

    /// Get the typst format argument for this format.
    pub fn typst_arg(&self) -> &'static str {
        match self {
            Format::Plain => panic!("Plain format should not be compiled"),
            Format::Svg => "svg",
            Format::Png => "png",
        }
    }
}

impl From<&str> for Format {
    fn from(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "plain" => Format::Plain,
            "svg" => Format::Svg,
            "png" => Format::Png,
            _ => Format::Png, // Default to PNG for unknown formats
        }
    }
}

/// Configuration for compiling Typst files.
#[derive(Debug, Clone)]
pub struct CompileConfig {
    /// The temporary Typst file to compile.
    pub temp_file: PathBuf,
    /// The source Typst file (for root directory calculation).
    pub source_file: PathBuf,
    /// Output directory for compiled files.
    pub output_dir: PathBuf,
    /// Additional arguments to pass to typst compile.
    pub extra_args: Vec<String>,
}

impl CompileConfig {
    /// Create a new compile configuration.
    pub fn new(temp_file: PathBuf, source_file: PathBuf, output_dir: PathBuf) -> Self {
        Self {
            temp_file,
            source_file,
            output_dir,
            extra_args: Vec::new(),
        }
    }

    /// Add extra arguments to the typst compile command.
    pub fn with_extra_args(mut self, args: Vec<String>) -> Self {
        self.extra_args = args;
        self
    }
}

/// Result of a compilation operation.
#[derive(Debug)]
pub struct CompileResult {
    /// The notes with associated media files.
    pub notes: Vec<Note>,
    /// Paths to generated output files.
    pub output_files: Vec<PathBuf>,
}

/// Compile a temporary Typst file and generate Anki notes.
///
/// This function:
/// 1. Queries the temporary file for note metadata
/// 2. Determines which formats need to be compiled
/// 3. Runs the appropriate typst compile commands
/// 4. Associates output files with notes and fields
/// 5. Returns structured note data for AnkiConnect
///
/// # Arguments
///
/// * `config` - Compilation configuration
///
/// # Returns
///
/// Returns a `CompileResult` containing the generated notes and output file paths.
///
/// # Errors
///
/// Returns an error if:
/// - The temporary file cannot be queried for metadata
/// - Typst compilation fails
/// - Output files cannot be read or renamed
pub async fn compile_temp_file(config: &CompileConfig) -> Result<CompileResult> {
    // Query the temporary file for note metadata
    let metadata_notes = query_notes_metadata(config).await?;

    if metadata_notes.is_empty() {
        return Ok(CompileResult {
            notes: Vec::new(),
            output_files: Vec::new(),
        });
    }

    // Determine which formats need to be compiled
    let required_formats = determine_required_formats(&metadata_notes);

    // Compile the files for each required format
    let mut output_files = Vec::new();
    for format in &required_formats {
        if *format != Format::Plain {
            let files = compile_format(config, format).await?;
            output_files.extend(files);
        }
    }

    // Associate output files with notes and fields
    let notes = associate_files_with_notes(config, &metadata_notes, &output_files).await?;

    Ok(CompileResult {
        notes,
        output_files,
    })
}

/// Query the temporary file for note metadata.
async fn query_notes_metadata(config: &CompileConfig) -> Result<Vec<MetadataNote>> {
    let root_dir = get_root_path()?;
    let root_arg = root_dir
        .to_str()
        .ok_or_else(|| Error::custom("Root directory path contains invalid UTF-8"))?;

    let extra_args = vec!["--root", root_arg];
    query_ankify_notes(&config.temp_file, Some(&extra_args)).await
}

/// Determine which formats need to be compiled based on note metadata.
fn determine_required_formats(notes: &[MetadataNote]) -> Vec<Format> {
    let mut formats = std::collections::HashSet::new();

    for note in notes {
        if let Some(note_format) = &note.format {
            formats.insert(Format::from(note_format.as_str()));
        } else {
            formats.insert(Format::Png); // Default format
        }

        // Check field-specific formats if data has format specifications
        for value in note.data.values() {
            if let crate::metadata::NoteDataValue::WithFormat(data) = value {
                if let Some(field_format) = &data.format {
                    formats.insert(Format::from(field_format.as_str()));
                }
            }
        }
    }

    formats.into_iter().collect()
}

/// Compile the temporary file for a specific format.
async fn compile_format(config: &CompileConfig, format: &Format) -> Result<Vec<PathBuf>> {
    // Use {p} pattern to generate one file per page
    let output_pattern = config
        .output_dir
        .join(format!("output-{{p}}.{}", format.extension()));

    let root_dir = get_root_path()?;

    // Build the typst compile command
    let mut cmd = AsyncCommand::new("typst");
    cmd.arg("compile")
        .arg("--format")
        .arg(format.typst_arg())
        .arg("--root")
        .arg(root_dir)
        .arg(&config.temp_file)
        .arg(&output_pattern);

    // Add any extra arguments
    for arg in &config.extra_args {
        cmd.arg(arg);
    }

    // Execute the command
    let output = cmd
        .output()
        .await
        .map_err(|e| Error::custom(format!("Failed to execute typst compile: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::custom(format!(
            "Typst compilation failed: {}",
            stderr
        )));
    }

    // Find all generated output files (output-1.ext, output-2.ext, etc.)
    let mut output_files = Vec::new();
    let output_dir = config.output_dir.as_path();

    if output_dir.exists() {
        let entries = fs::read_dir(output_dir).map_err(|e| {
            Error::custom(format!(
                "Failed to read output directory {}: {}",
                output_dir.display(),
                e
            ))
        })?;

        for entry in entries {
            let entry = entry
                .map_err(|e| Error::custom(format!("Failed to read directory entry: {}", e)))?;

            let path = entry.path();
            if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                // Check for pattern: output-<number>.extension
                if filename.starts_with("output-")
                    && path
                        .extension()
                        .map_or(false, |ext| ext == format.extension())
                {
                    output_files.push(path);
                }
            }
        }
    }

    // Sort output files by page number to ensure consistent ordering
    output_files.sort_by(|a, b| {
        let extract_page_num = |path: &PathBuf| -> u32 {
            path.file_stem()
                .and_then(|stem| stem.to_str())
                .and_then(|s| s.strip_prefix("output-"))
                .and_then(|s| s.parse().ok())
                .unwrap_or(0)
        };
        extract_page_num(a).cmp(&extract_page_num(b))
    });

    Ok(output_files)
}

/// Associate output files with notes and fields.
async fn associate_files_with_notes(
    _config: &CompileConfig,
    metadata_notes: &[MetadataNote],
    output_files: &[PathBuf],
) -> Result<Vec<Note>> {
    let mut anki_notes = Vec::new();
    let timestamp = chrono::Utc::now().timestamp();

    // Create a mapping of (note_index, field_name) to output file
    let file_associations = create_file_associations(metadata_notes, output_files)?;

    for (note_index, metadata_note) in metadata_notes.iter().enumerate() {
        let mut fields = HashMap::new();
        let mut picture_files = Vec::new();

        // Sort field names to ensure consistent ordering (as per documentation)
        let mut sorted_fields: Vec<_> = metadata_note.data.keys().collect();
        sorted_fields.sort();

        for field_name in sorted_fields {
            let field_value = &metadata_note.data[field_name];

            // Determine the format for this field
            let field_format = get_field_format(field_value, &metadata_note.format);

            match field_format {
                Format::Plain => {
                    // For plain format, use the string value directly
                    let text_content = extract_text_content(field_value);
                    fields.insert(
                        Field::new(field_name.clone()),
                        FieldValue::new(text_content),
                    );
                }
                _ => {
                    // For image formats, create media file and reference it
                    if let Some(output_file) =
                        file_associations.get(&(note_index, field_name.as_str()))
                    {
                        let media_file = create_media_file(
                            output_file,
                            &metadata_note.label,
                            field_name,
                            timestamp,
                            &field_format,
                        )?;

                        // Add reference to the field
                        let filename = media_file.filename.clone();
                        fields.insert(
                            Field::new(field_name.clone()),
                            FieldValue::new(format!("<img src=\"{}\">", filename)),
                        );

                        picture_files.push(media_file);
                    } else {
                        // Fallback to text content if no output file found
                        let text_content = extract_text_content(field_value);
                        fields.insert(
                            Field::new(field_name.clone()),
                            FieldValue::new(text_content),
                        );
                    }
                }
            }
        }

        // Create the Anki note
        let anki_note = Note {
            deck_name: Deck::new(metadata_note.deck.clone()),
            model_name: Model::new(metadata_note.model.clone()),
            fields,
            tags: Some(
                metadata_note
                    .tags
                    .iter()
                    .map(|tag| Tag::new(tag.clone()))
                    .collect(),
            ),
            options: None,
            audio: None,
            video: None,
            picture: if picture_files.is_empty() {
                None
            } else {
                Some(picture_files)
            },
        };

        anki_notes.push(anki_note);
    }

    Ok(anki_notes)
}

/// Create a mapping of (note_index, field_name) to output file.
fn create_file_associations<'a>(
    metadata_notes: &'a [MetadataNote],
    output_files: &'a [PathBuf],
) -> Result<HashMap<(usize, &'a str), &'a PathBuf>> {
    let mut associations = HashMap::new();
    let mut file_index = 0;

    for (note_index, metadata_note) in metadata_notes.iter().enumerate() {
        // Sort field names to match the order used in the generated Typst file
        let mut sorted_fields: Vec<_> = metadata_note.data.keys().collect();
        sorted_fields.sort();

        for field_name in sorted_fields {
            let field_value = &metadata_note.data[field_name];
            let field_format = get_field_format(field_value, &metadata_note.format);

            // Only associate files for non-plain formats
            if field_format != Format::Plain {
                if file_index < output_files.len() {
                    associations
                        .insert((note_index, field_name.as_str()), &output_files[file_index]);
                    file_index += 1;
                }
            }
        }
    }

    Ok(associations)
}

/// Get the format for a specific field.
fn get_field_format(
    field_value: &crate::metadata::NoteDataValue,
    note_format: &Option<String>,
) -> Format {
    match field_value {
        crate::metadata::NoteDataValue::WithFormat(data) => {
            if let Some(format) = &data.format {
                Format::from(format.as_str())
            } else if let Some(note_fmt) = note_format {
                Format::from(note_fmt.as_str())
            } else {
                Format::Png
            }
        }
        _ => {
            if let Some(note_fmt) = note_format {
                Format::from(note_fmt.as_str())
            } else {
                Format::Png
            }
        }
    }
}

/// Extract text content from a note data value.
fn extract_text_content(value: &crate::metadata::NoteDataValue) -> String {
    match value {
        crate::metadata::NoteDataValue::Simple(text) => text.clone(),
        crate::metadata::NoteDataValue::WithFormat(data) => data.value.clone(),
        crate::metadata::NoteDataValue::Complex(_) => {
            // For complex content, we could render it as text, but for now just use a placeholder
            "[Complex Content]".to_string()
        }
    }
}

/// Create a media file from an output file.
fn create_media_file(
    output_file: &Path,
    note_label: &str,
    field_name: &str,
    timestamp: i64,
    format: &Format,
) -> Result<MediaFile> {
    // Read the file content
    let file_data = fs::read(output_file).map_err(|e| {
        Error::custom(format!(
            "Failed to read output file {}: {}",
            output_file.display(),
            e
        ))
    })?;

    // Encode as base64
    let encoded_data = base64::engine::general_purpose::STANDARD.encode(&file_data);

    // Generate the filename using the specified format
    let filename = format!(
        "{}@@{}@@{}.{}",
        note_label,
        field_name,
        timestamp,
        format.extension()
    );

    Ok(MediaFile {
        filename,
        data: Some(encoded_data),
        path: None,
        url: None,
        skip_hash: None,
        fields: None,
    })
}

/// Clean up output files in the given directory.
///
/// This function removes all files matching the pattern `output-*` in the
/// specified directory.
///
/// # Arguments
///
/// * `dir` - The directory to clean up
///
/// # Errors
///
/// Returns an error if the directory cannot be read or files cannot be removed.
pub fn cleanup_output_files(dir: &Path) -> Result<()> {
    if !dir.exists() {
        return Ok(()); // Nothing to clean up
    }

    let entries = fs::read_dir(dir)
        .map_err(|e| Error::custom(format!("Failed to read directory {}: {}", dir.display(), e)))?;

    for entry in entries {
        let entry = entry.map_err(|e| {
            Error::custom(format!(
                "Failed to read directory entry in {}: {}",
                dir.display(),
                e
            ))
        })?;

        let path = entry.path();
        if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
            // Clean up both pattern: output-<number>.ext and temp render files
            if filename.starts_with("output-") || filename.ends_with("_render.typ") {
                fs::remove_file(&path).map_err(|e| {
                    Error::custom(format!(
                        "Failed to remove output file {}: {}",
                        path.display(),
                        e
                    ))
                })?;
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metadata::NoteDataValue;
    use std::collections::HashMap;
    use tempfile::TempDir;

    #[test]
    fn test_format_from_str() {
        assert_eq!(Format::from("plain"), Format::Plain);
        assert_eq!(Format::from("svg"), Format::Svg);
        assert_eq!(Format::from("png"), Format::Png);
        assert_eq!(Format::from("PNG"), Format::Png);
        assert_eq!(Format::from("unknown"), Format::Png);
    }

    #[test]
    fn test_format_extension() {
        assert_eq!(Format::Plain.extension(), "txt");
        assert_eq!(Format::Svg.extension(), "svg");
        assert_eq!(Format::Png.extension(), "png");
    }

    #[test]
    fn test_format_typst_arg() {
        assert_eq!(Format::Svg.typst_arg(), "svg");
        assert_eq!(Format::Png.typst_arg(), "png");
    }

    #[test]
    #[should_panic(expected = "Plain format should not be compiled")]
    fn test_format_plain_typst_arg_panics() {
        Format::Plain.typst_arg();
    }

    #[test]
    fn test_compile_config_new() {
        let temp_file = PathBuf::from("temp.typ");
        let source_file = PathBuf::from("source.typ");
        let output_dir = PathBuf::from("output");

        let config = CompileConfig::new(temp_file.clone(), source_file.clone(), output_dir.clone());

        assert_eq!(config.temp_file, temp_file);
        assert_eq!(config.source_file, source_file);
        assert_eq!(config.output_dir, output_dir);
        assert!(config.extra_args.is_empty());
    }

    #[test]
    fn test_compile_config_with_extra_args() {
        let config = CompileConfig::new(
            PathBuf::from("temp.typ"),
            PathBuf::from("source.typ"),
            PathBuf::from("output"),
        )
        .with_extra_args(vec!["--verbose".to_string()]);

        assert_eq!(config.extra_args, vec!["--verbose"]);
    }

    #[test]
    fn test_determine_required_formats() {
        let mut notes = Vec::new();

        // Note with PNG format
        let mut note1 = MetadataNote {
            label: "note1".to_string(),
            model: "Basic".to_string(),
            data: HashMap::new(),
            deck: "Test".to_string(),
            tags: Vec::new(),
            other: serde_json::Value::Null,
            format: Some("png".to_string()),
        };
        note1.data.insert(
            "Front".to_string(),
            NoteDataValue::Simple("Question".to_string()),
        );

        // Note with SVG format
        let mut note2 = MetadataNote {
            label: "note2".to_string(),
            model: "Basic".to_string(),
            data: HashMap::new(),
            deck: "Test".to_string(),
            tags: Vec::new(),
            other: serde_json::Value::Null,
            format: Some("svg".to_string()),
        };
        note2.data.insert(
            "Front".to_string(),
            NoteDataValue::Simple("Question".to_string()),
        );

        notes.push(note1);
        notes.push(note2);

        let formats = determine_required_formats(&notes);
        assert!(formats.contains(&Format::Png));
        assert!(formats.contains(&Format::Svg));
    }

    #[test]
    fn test_get_field_format() {
        // Simple value with note format
        let simple_value = NoteDataValue::Simple("test".to_string());
        let format = get_field_format(&simple_value, &Some("svg".to_string()));
        assert_eq!(format, Format::Svg);

        // WithFormat value with specific format
        let with_format_value =
            NoteDataValue::WithFormat(crate::metadata::NoteDataValueWithFormat {
                value: "test".to_string(),
                format: Some("png".to_string()),
            });
        let format = get_field_format(&with_format_value, &Some("svg".to_string()));
        assert_eq!(format, Format::Png);

        // Default format
        let format = get_field_format(&simple_value, &None);
        assert_eq!(format, Format::Png);
    }

    #[test]
    fn test_extract_text_content() {
        // Simple value
        let simple = NoteDataValue::Simple("test content".to_string());
        assert_eq!(extract_text_content(&simple), "test content");

        // WithFormat value
        let with_format = NoteDataValue::WithFormat(crate::metadata::NoteDataValueWithFormat {
            value: "formatted content".to_string(),
            format: Some("png".to_string()),
        });
        assert_eq!(extract_text_content(&with_format), "formatted content");

        // Complex value
        let complex = NoteDataValue::Complex(serde_json::json!({"func": "test"}));
        assert_eq!(extract_text_content(&complex), "[Complex Content]");
    }

    #[test]
    fn test_create_media_file() {
        let temp_dir = TempDir::new().unwrap();
        let test_file = temp_dir.path().join("test.png");
        fs::write(&test_file, b"test image data").unwrap();

        let media_file =
            create_media_file(&test_file, "test-note", "Front", 1234567890, &Format::Png).unwrap();

        assert_eq!(media_file.filename, "test-note@@Front@@1234567890.png");
        assert!(media_file.data.is_some());
        assert_eq!(
            media_file.data.unwrap(),
            base64::engine::general_purpose::STANDARD.encode(b"test image data")
        );
        assert!(media_file.path.is_none());
        assert!(media_file.url.is_none());
    }

    #[test]
    fn test_cleanup_output_files() {
        let temp_dir = TempDir::new().unwrap();
        let temp_path = temp_dir.path();

        // Create various test files
        fs::write(temp_path.join("output-1.png"), "content").unwrap();
        fs::write(temp_path.join("output-2.svg"), "content").unwrap();
        fs::write(temp_path.join("keep_this.png"), "keep this").unwrap();
        fs::write(temp_path.join("document.typ"), "keep this too").unwrap();

        // Clean up output files
        cleanup_output_files(temp_path).unwrap();

        // Check that only output files were removed
        assert!(!temp_path.join("output-1.png").exists());
        assert!(!temp_path.join("output-2.svg").exists());
        assert!(temp_path.join("keep_this.png").exists());
        assert!(temp_path.join("document.typ").exists());
    }

    #[test]
    fn test_cleanup_output_files_nonexistent_directory() {
        let temp_dir = TempDir::new().unwrap();
        let nonexistent = temp_dir.path().join("nonexistent");

        let result = cleanup_output_files(&nonexistent);
        assert!(result.is_ok()); // Should not error for non-existent directories
    }
}
